### ISSUE TITLE
building project fail

### ISSUE THREAD

**Issue by irdispsyhonikum** [peakhunt/chinese-diesel-heater-esp32#2]
Hello. 

I am new in all this staff and in coding. can you tell me please, what I am doing wrong when building you project?

Here is a terminal output:
`[806/860] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/heater/gpio.c.obj
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/heater/gpio.c.obj 
/home/gach/.espressif/tools/xtensa-esp32-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -Iconfig -I../main -I../main/heater -I../main/display -I../main/utils -I../../../components/newlib/platform_include -I../../../components/freertos/FreeRTOS-Kernel/include -I../../../components/freertos/esp_additions/include/freertos -I../../../components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I../../../components/freertos/esp_additions/include -I../../../components/esp_hw_support/include -I../../../components/esp_hw_support/include/soc -I../../../components/esp_hw_support/include/soc/esp32 -I../../../components/esp_hw_support/port/esp32/. -I../../../components/esp_hw_support/port/esp32/private_include -I../../../components/heap/include -I../../../components/log/include -I../../../components/soc/include -I../../../components/soc/esp32/. -I../../../components/soc/esp32/include -I../../../components/hal/esp32/include -I../../../components/hal/include -I../../../components/hal/platform_port/include -I../../../components/esp_rom/include -I../../../components/esp_rom/include/esp32 -I../../../components/esp_rom/esp32 -I../../../components/esp_common/include -I../../../components/esp_system/include -I../../../components/esp_system/port/soc -I../../../components/esp_system/port/include/private -I../../../components/xtensa/include -I../../../components/xtensa/esp32/include -I../../../components/lwip/include/apps -I../../../components/lwip/include/apps/sntp -I../../../components/lwip/lwip/src/include -I../../../components/lwip/port/esp32/include -I../../../components/lwip/port/esp32/include/arch -I../../../components/vfs/include -I../../../components/esp_wifi/include -I../../../components/esp_event/include -I../../../components/esp_netif/include -I../../../components/esp_eth/include -I../../../components/esp_phy/include -I../../../components/esp_phy/esp32/include -I../../../components/esp_ringbuf/include -I../../../components/efuse/include -I../../../components/efuse/esp32/include -I../../../components/driver/include -I../../../components/driver/deprecated -I../../../components/driver/esp32/include -I../../../components/esp_pm/include -I../../../components/mbedtls/port/include -I../../../components/mbedtls/mbedtls/include -I../../../components/mbedtls/mbedtls/library -I../../../components/mbedtls/esp_crt_bundle/include -I../../../components/app_update/include -I../../../components/spi_flash/include -I../../../components/bootloader_support/include -I../../../components/bootloader_support/bootloader_flash/include -I../../../components/pthread/include -I../../../components/esp_timer/include -I../../../components/app_trace/include -I../../../components/nvs_flash/include -I../../../components/wpa_supplicant/include -I../../../components/wpa_supplicant/port/include -I../../../components/wpa_supplicant/esp_supplicant/include -I../../../components/asio/asio/asio/include -I../../../components/asio/port/include -I../../../components/unity/include -I../../../components/unity/unity/src -I../../../components/cmock/CMock/src -I../../../components/console -I../../../components/http_parser -I../../../components/esp-tls -I../../../components/esp-tls/esp-tls-crypto -I../../../components/esp_adc_cal/include -I../../../components/esp_gdbstub/include -I../../../components/esp_gdbstub/xtensa -I../../../components/esp_gdbstub/esp32 -I../../../components/esp_hid/include -I../../../components/tcp_transport/include -I../../../components/esp_http_client/include -I../../../components/esp_http_server/include -I../../../components/esp_https_ota/include -I../../../components/esp_lcd/include -I../../../components/esp_lcd/interface -I../../../components/protobuf-c/protobuf-c -I../../../components/protocomm/include/common -I../../../components/protocomm/include/security -I../../../components/protocomm/include/transports -I../../../components/mdns/include -I../../../components/esp_local_ctrl/include -I../../../components/sdmmc/include -I../../../components/esp_serial_slave_link/include -I../../../components/espcoredump/include -I../../../components/espcoredump/include/port/xtensa -I../../../components/wear_levelling/include -I../../../components/fatfs/diskio -I../../../components/fatfs/vfs -I../../../components/fatfs/src -I../../../components/idf_test/include -I../../../components/idf_test/include/esp32 -I../../../components/ieee802154/include -I../../../components/json/cJSON -I../../../components/mqtt/esp-mqtt/include -I../../../components/perfmon/include -I../../../components/spiffs/include -I../../../components/ulp/ulp_common/include -I../../../components/ulp/ulp_common/include/esp32 -I../../../components/wifi_provisioning/include -mlongcalls -Wno-frame-address    -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -gdwarf-4 -ggdb -Og -fmacro-prefix-map=/home/gach/esp/esp-idf/projects/heater=. -fmacro-prefix-map=/home/gach/esp/esp-idf=/IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -DconfigENABLE_FREERTOS_DEBUG_OCDAWARE=1 -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v5.0-dev-3290-g01d014c42d\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/heater/gpio.c.obj -MF esp-idf/main/CMakeFiles/__idf_main.dir/heater/gpio.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/heater/gpio.c.obj   -c ../main/heater/gpio.c
../main/heater/gpio.c:84:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'gpio_isr_handler'
 gpio_isr_handler(void* arg)
 ^~~~~~~~~~~~~~~~
../main/heater/gpio.c: In function 'init_input_pins':
../main/heater/gpio.c:195:27: error: 'GPIO_PIN_INTR_ANYEDGE' undeclared (first use in this function); did you mean 'GPIO_INTR_ANYEDGE'?
   io_conf.intr_type     = GPIO_PIN_INTR_ANYEDGE;
                           ^~~~~~~~~~~~~~~~~~~~~
                           GPIO_INTR_ANYEDGE
../main/heater/gpio.c:195:27: note: each undeclared identifier is reported only once for each function it appears in
../main/heater/gpio.c:227:36: error: 'gpio_isr_handler' undeclared (first use in this function); did you mean 'gpio_isr_handle_t'?
   gpio_isr_handler_add(GPIO_PIN25, gpio_isr_handler, (void*) GPIO_PIN25);
                                    ^~~~~~~~~~~~~~~~
                                    gpio_isr_handle_t
../main/heater/gpio.c: In function 'gpio_init':
../main/heater/gpio.c:246:3: error: implicit declaration of function 'gpio_pad_select_gpio'; did you mean 'esp_rom_gpio_pad_select_gpio'? [-Werror=implicit-function-declaration]
   gpio_pad_select_gpio(GPIO_PIN5);
   ^~~~~~~~~~~~~~~~~~~~
   esp_rom_gpio_pad_select_gpio
cc1: some warnings being treated as errors
[811/860] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/rest_server.c.obj
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/rest_server.c.obj 
/home/gach/.espressif/tools/xtensa-esp32-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -Iconfig -I../main -I../main/heater -I../main/display -I../main/utils -I../../../components/newlib/platform_include -I../../../components/freertos/FreeRTOS-Kernel/include -I../../../components/freertos/esp_additions/include/freertos -I../../../components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I../../../components/freertos/esp_additions/include -I../../../components/esp_hw_support/include -I../../../components/esp_hw_support/include/soc -I../../../components/esp_hw_support/include/soc/esp32 -I../../../components/esp_hw_support/port/esp32/. -I../../../components/esp_hw_support/port/esp32/private_include -I../../../components/heap/include -I../../../components/log/include -I../../../components/soc/include -I../../../components/soc/esp32/. -I../../../components/soc/esp32/include -I../../../components/hal/esp32/include -I../../../components/hal/include -I../../../components/hal/platform_port/include -I../../../components/esp_rom/include -I../../../components/esp_rom/include/esp32 -I../../../components/esp_rom/esp32 -I../../../components/esp_common/include -I../../../components/esp_system/include -I../../../components/esp_system/port/soc -I../../../components/esp_system/port/include/private -I../../../components/xtensa/include -I../../../components/xtensa/esp32/include -I../../../components/lwip/include/apps -I../../../components/lwip/include/apps/sntp -I../../../components/lwip/lwip/src/include -I../../../components/lwip/port/esp32/include -I../../../components/lwip/port/esp32/include/arch -I../../../components/vfs/include -I../../../components/esp_wifi/include -I../../../components/esp_event/include -I../../../components/esp_netif/include -I../../../components/esp_eth/include -I../../../components/esp_phy/include -I../../../components/esp_phy/esp32/include -I../../../components/esp_ringbuf/include -I../../../components/efuse/include -I../../../components/efuse/esp32/include -I../../../components/driver/include -I../../../components/driver/deprecated -I../../../components/driver/esp32/include -I../../../components/esp_pm/include -I../../../components/mbedtls/port/include -I../../../components/mbedtls/mbedtls/include -I../../../components/mbedtls/mbedtls/library -I../../../components/mbedtls/esp_crt_bundle/include -I../../../components/app_update/include -I../../../components/spi_flash/include -I../../../components/bootloader_support/include -I../../../components/bootloader_support/bootloader_flash/include -I../../../components/pthread/include -I../../../components/esp_timer/include -I../../../components/app_trace/include -I../../../components/nvs_flash/include -I../../../components/wpa_supplicant/include -I../../../components/wpa_supplicant/port/include -I../../../components/wpa_supplicant/esp_supplicant/include -I../../../components/asio/asio/asio/include -I../../../components/asio/port/include -I../../../components/unity/include -I../../../components/unity/unity/src -I../../../components/cmock/CMock/src -I../../../components/console -I../../../components/http_parser -I../../../components/esp-tls -I../../../components/esp-tls/esp-tls-crypto -I../../../components/esp_adc_cal/include -I../../../components/esp_gdbstub/include -I../../../components/esp_gdbstub/xtensa -I../../../components/esp_gdbstub/esp32 -I../../../components/esp_hid/include -I../../../components/tcp_transport/include -I../../../components/esp_http_client/include -I../../../components/esp_http_server/include -I../../../components/esp_https_ota/include -I../../../components/esp_lcd/include -I../../../components/esp_lcd/interface -I../../../components/protobuf-c/protobuf-c -I../../../components/protocomm/include/common -I../../../components/protocomm/include/security -I../../../components/protocomm/include/transports -I../../../components/mdns/include -I../../../components/esp_local_ctrl/include -I../../../components/sdmmc/include -I../../../components/esp_serial_slave_link/include -I../../../components/espcoredump/include -I../../../components/espcoredump/include/port/xtensa -I../../../components/wear_levelling/include -I../../../components/fatfs/diskio -I../../../components/fatfs/vfs -I../../../components/fatfs/src -I../../../components/idf_test/include -I../../../components/idf_test/include/esp32 -I../../../components/ieee802154/include -I../../../components/json/cJSON -I../../../components/mqtt/esp-mqtt/include -I../../../components/perfmon/include -I../../../components/spiffs/include -I../../../components/ulp/ulp_common/include -I../../../components/ulp/ulp_common/include/esp32 -I../../../components/wifi_provisioning/include -mlongcalls -Wno-frame-address    -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -gdwarf-4 -ggdb -Og -fmacro-prefix-map=/home/gach/esp/esp-idf/projects/heater=. -fmacro-prefix-map=/home/gach/esp/esp-idf=/IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -DconfigENABLE_FREERTOS_DEBUG_OCDAWARE=1 -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v5.0-dev-3290-g01d014c42d\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/rest_server.c.obj -MF esp-idf/main/CMakeFiles/__idf_main.dir/rest_server.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/rest_server.c.obj   -c ../main/rest_server.c
../main/rest_server.c: In function 'system_info_get_handler':
../main/rest_server.c:179:3: error: unknown type name 'esp_chip_info_t'; did you mean 'esp_vfs_id_t'?
   esp_chip_info_t chip_info;
   ^~~~~~~~~~~~~~~
   esp_vfs_id_t
../main/rest_server.c:180:3: error: implicit declaration of function 'esp_chip_info' [-Werror=implicit-function-declaration]
   esp_chip_info(&chip_info);
   ^~~~~~~~~~~~~
../main/rest_server.c:182:51: error: request for member 'cores' in something not a structure or union
   cJSON_AddNumberToObject(root, "cores", chip_info.cores);
                                                   ^
cc1: some warnings being treated as errors
[815/860] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/app_main.c.obj
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/app_main.c.obj 
/home/gach/.espressif/tools/xtensa-esp32-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -Iconfig -I../main -I../main/heater -I../main/display -I../main/utils -I../../../components/newlib/platform_include -I../../../components/freertos/FreeRTOS-Kernel/include -I../../../components/freertos/esp_additions/include/freertos -I../../../components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I../../../components/freertos/esp_additions/include -I../../../components/esp_hw_support/include -I../../../components/esp_hw_support/include/soc -I../../../components/esp_hw_support/include/soc/esp32 -I../../../components/esp_hw_support/port/esp32/. -I../../../components/esp_hw_support/port/esp32/private_include -I../../../components/heap/include -I../../../components/log/include -I../../../components/soc/include -I../../../components/soc/esp32/. -I../../../components/soc/esp32/include -I../../../components/hal/esp32/include -I../../../components/hal/include -I../../../components/hal/platform_port/include -I../../../components/esp_rom/include -I../../../components/esp_rom/include/esp32 -I../../../components/esp_rom/esp32 -I../../../components/esp_common/include -I../../../components/esp_system/include -I../../../components/esp_system/port/soc -I../../../components/esp_system/port/include/private -I../../../components/xtensa/include -I../../../components/xtensa/esp32/include -I../../../components/lwip/include/apps -I../../../components/lwip/include/apps/sntp -I../../../components/lwip/lwip/src/include -I../../../components/lwip/port/esp32/include -I../../../components/lwip/port/esp32/include/arch -I../../../components/vfs/include -I../../../components/esp_wifi/include -I../../../components/esp_event/include -I../../../components/esp_netif/include -I../../../components/esp_eth/include -I../../../components/esp_phy/include -I../../../components/esp_phy/esp32/include -I../../../components/esp_ringbuf/include -I../../../components/efuse/include -I../../../components/efuse/esp32/include -I../../../components/driver/include -I../../../components/driver/deprecated -I../../../components/driver/esp32/include -I../../../components/esp_pm/include -I../../../components/mbedtls/port/include -I../../../components/mbedtls/mbedtls/include -I../../../components/mbedtls/mbedtls/library -I../../../components/mbedtls/esp_crt_bundle/include -I../../../components/app_update/include -I../../../components/spi_flash/include -I../../../components/bootloader_support/include -I../../../components/bootloader_support/bootloader_flash/include -I../../../components/pthread/include -I../../../components/esp_timer/include -I../../../components/app_trace/include -I../../../components/nvs_flash/include -I../../../components/wpa_supplicant/include -I../../../components/wpa_supplicant/port/include -I../../../components/wpa_supplicant/esp_supplicant/include -I../../../components/asio/asio/asio/include -I../../../components/asio/port/include -I../../../components/unity/include -I../../../components/unity/unity/src -I../../../components/cmock/CMock/src -I../../../components/console -I../../../components/http_parser -I../../../components/esp-tls -I../../../components/esp-tls/esp-tls-crypto -I../../../components/esp_adc_cal/include -I../../../components/esp_gdbstub/include -I../../../components/esp_gdbstub/xtensa -I../../../components/esp_gdbstub/esp32 -I../../../components/esp_hid/include -I../../../components/tcp_transport/include -I../../../components/esp_http_client/include -I../../../components/esp_http_server/include -I../../../components/esp_https_ota/include -I../../../components/esp_lcd/include -I../../../components/esp_lcd/interface -I../../../components/protobuf-c/protobuf-c -I../../../components/protocomm/include/common -I../../../components/protocomm/include/security -I../../../components/protocomm/include/transports -I../../../components/mdns/include -I../../../components/esp_local_ctrl/include -I../../../components/sdmmc/include -I../../../components/esp_serial_slave_link/include -I../../../components/espcoredump/include -I../../../components/espcoredump/include/port/xtensa -I../../../components/wear_levelling/include -I../../../components/fatfs/diskio -I../../../components/fatfs/vfs -I../../../components/fatfs/src -I../../../components/idf_test/include -I../../../components/idf_test/include/esp32 -I../../../components/ieee802154/include -I../../../components/json/cJSON -I../../../components/mqtt/esp-mqtt/include -I../../../components/perfmon/include -I../../../components/spiffs/include -I../../../components/ulp/ulp_common/include -I../../../components/ulp/ulp_common/include/esp32 -I../../../components/wifi_provisioning/include -mlongcalls -Wno-frame-address    -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -gdwarf-4 -ggdb -Og -fmacro-prefix-map=/home/gach/esp/esp-idf/projects/heater=. -fmacro-prefix-map=/home/gach/esp/esp-idf=/IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -DconfigENABLE_FREERTOS_DEBUG_OCDAWARE=1 -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v5.0-dev-3290-g01d014c42d\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/app_main.c.obj -MF esp-idf/main/CMakeFiles/__idf_main.dir/app_main.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/app_main.c.obj   -c ../main/app_main.c
../main/app_main.c: In function 'app_main':
../main/app_main.c:38:3: error: unknown type name 'esp_chip_info_t'; did you mean 'esp_netif_ip_info_t'?
   esp_chip_info_t chip_info;
   ^~~~~~~~~~~~~~~
   esp_netif_ip_info_t
../main/app_main.c:39:3: error: implicit declaration of function 'esp_chip_info'; did you mean 'esp_netif_init'? [-Werror=implicit-function-declaration]
   esp_chip_info(&chip_info);
   ^~~~~~~~~~~~~
   esp_netif_init
../main/app_main.c:43:16: error: request for member 'cores' in something not a structure or union
       chip_info.cores,
                ^
../main/app_main.c:44:17: error: request for member 'features' in something not a structure or union
       (chip_info.features & CHIP_FEATURE_BT) ? "/BT" : "",
                 ^
../main/app_main.c:44:29: error: 'CHIP_FEATURE_BT' undeclared (first use in this function)
       (chip_info.features & CHIP_FEATURE_BT) ? "/BT" : "",
                             ^~~~~~~~~~~~~~~
../main/app_main.c:44:29: note: each undeclared identifier is reported only once for each function it appears in
../main/app_main.c:45:17: error: request for member 'features' in something not a structure or union
       (chip_info.features & CHIP_FEATURE_BLE) ? "/BLE" : "");
                 ^
../main/app_main.c:45:29: error: 'CHIP_FEATURE_BLE' undeclared (first use in this function)
       (chip_info.features & CHIP_FEATURE_BLE) ? "/BLE" : "");
                             ^~~~~~~~~~~~~~~~
../main/app_main.c:47:44: error: request for member 'revision' in something not a structure or union
   printf("silicon revision %d, ", chip_info.revision);
                                            ^
../main/app_main.c:50:17: error: request for member 'features' in something not a structure or union
       (chip_info.features & CHIP_FEATURE_EMB_FLASH) ? "embedded" : "external");
                 ^
../main/app_main.c:50:29: error: 'CHIP_FEATURE_EMB_FLASH' undeclared (first use in this function)
       (chip_info.features & CHIP_FEATURE_EMB_FLASH) ? "embedded" : "external");
                             ^~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
[823/860] Building CXX object esp-idf/asio/CMakeFiles/__idf_asio.dir/asio/asio/src/asio.cpp.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
`

can you please help me with that?

**Comment by peakhunt** [comment]
Hello,

let me briefly tell you the build process

1. you have to install vue-cli to build web front-end. It depends on npm environment you are using but basically you can install it with "npm install -g @vue/cli"

2. then, you have to build webt-front
   cd web-front
   npm install
   npm run build

3. then, using idf.py, you should build the esp32 firmware
   idf.py build

According to the error output you pasted, I think there is a problem with your ESP-IDF setup before building.

I just reiterated the whole build process on my machine and I didn't have any issue. I'm using ESP-IDF v4.3.1.
And I won't go into all the details of setting up ESP-IDF SDK and sourcing build environment variables.

Hope this helped

**Comment by irdispsyhonikum** [comment]
Hello.

Thank you for your reply.

I did all as you sad. And stack on 3rd task. Thank you for the way where to
look for a problemm. May-be I had not installed all tools. Will have look
for that.
Thank you so much.

Kind regards
Jurijs


P.S. do you want me to delete issue?

чт, 9 июн. 2022 г., 01:01 Huckleberry K. ***@***.***>:
